language: c
sudo: false

# Caching so the next build will be fast too.
cache:
  apt: true
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work/install

matrix:
  include:
  - env: GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml GHCOPTS=-Werror
    compiler: ': #GHC 7.8.4 Pandoc 1.16'
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
  - env: GHCVER=7.10.3 STACK_YAML=stack.yaml GHCOPTS=-Werror
    compiler: ': #GHC 7.10.3 Pandoc 1.16'
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3
  - env: GHCVER=7.10.3 STACK_YAML=stack-pandoc-1.17.yaml GHCOPTS=-Werror
    compiler: ': #GHC 7.10.3 Pandoc 1.17'
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3

before_install:
- unset CC
# Download and unpack the stack executable
- export PATH=/opt/ghc/$GHCVER/bin:$PATH
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
script:
  - stack --no-terminal --skip-ghc-check test
